version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
